# Generated by Django 4.0.6 on 2022-08-31 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0002_student_madrasha_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='madrasha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='madrasha_students', to='accounts.madrasha'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
