# Generated by Django 4.0.6 on 2022-10-01 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_madrasha_alter_student_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-slug']},
        ),
    ]
