# Generated by Django 4.1.2 on 2022-10-27 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_mealinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealinfo',
            name='meal_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 27, 6, 56, 13, 666615, tzinfo=datetime.timezone.utc)),
        ),
    ]
