# Generated by Django 4.0.6 on 2022-10-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='occupation',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('farmer', 'Farmer'), ('doctor', 'Doctor'), ('police', 'Police'), ('businessman', 'Businessman'), ('govt-employee', 'Govt. employee'), ('non-govt-employee', 'Non govt. employee'), ('other', 'Other')], default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_occupation',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('farmer', 'Farmer'), ('doctor', 'Doctor'), ('police', 'Police'), ('businessman', 'Businessman'), ('govt-employee', 'Govt. employee'), ('non-govt-employee', 'Non govt. employee'), ('other', 'Other')], default='null', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_relation',
            field=models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('brother', 'Brother'), ('sister', 'Sister'), ('uncle', 'Uncle'), ('aunty', 'Aunty'), ('cousin', 'Cousin')], default='father', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='other_contact_person_relation',
            field=models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('brother', 'Brother'), ('sister', 'Sister'), ('uncle', 'Uncle'), ('aunty', 'Aunty'), ('cousin', 'Cousin')], max_length=20, null=True),
        ),
    ]
