# Generated by Django 4.1.2 on 2022-10-27 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_mealinfo_meal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealinfo',
            name='meal_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 27, 6, 57, 20, 975756, tzinfo=datetime.timezone.utc)),
        ),
    ]
