# Generated by Django 4.1.2 on 2022-10-18 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BazarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bazar_item_name', models.CharField(max_length=250)),
                ('quantity', models.CharField(max_length=250)),
                ('measurement', models.CharField(choices=[('kg', 'Kg'), ('litre', 'Litre'), ('gm', 'Gm')], default='Kg', max_length=10)),
                ('amount', models.CharField(max_length=250)),
                ('consumption', models.CharField(max_length=250)),
                ('total_stock', models.CharField(blank=True, max_length=250, null=True)),
                ('madrasha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bazarItem_madrasha', to='accounts.madrasha')),
            ],
        ),
        migrations.CreateModel(
            name='BazarList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('total_cost', models.CharField(blank=True, max_length=250, null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bazarList_item', to='boarding.bazaritem')),
                ('madrasha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bazarList_madrasha', to='accounts.madrasha')),
            ],
        ),
    ]
