# Generated by Django 4.0.6 on 2022-09-28 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BazarList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('bazar_item_name', models.CharField(max_length=250)),
                ('quantity', models.CharField(max_length=250)),
                ('amount', models.CharField(max_length=250)),
                ('consumption', models.CharField(max_length=250)),
                ('current_stock', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('madrasha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bazarList_madrasha', to='accounts.madrasha')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
