# Generated by Django 4.0.6 on 2022-10-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boarding', '0003_alter_bazarlist_options_remove_bazarlist_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bazarlist',
            options={},
        ),
        migrations.AddField(
            model_name='bazaritem',
            name='measurement',
            field=models.CharField(choices=[('kg', 'Kg'), ('litre', 'Litre'), ('gm', 'Gm')], default='Kg', max_length=10),
        ),
    ]
