# Generated by Django 4.0.6 on 2022-10-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boarding', '0004_bazaritem_measurement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bazarlist',
            options={},
        ),
    ]
