# Generated by Django 4.0.6 on 2022-10-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boarding', '0004_alter_bazarlist_options_bazaritem_measurement'),
        ('boarding', '0005_alter_bazarlist_options'),
    ]

    operations = [
    ]
