# Generated by Django 4.0.6 on 2022-08-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madrasha',
            name='madrasha_logo',
            field=models.ImageField(blank=True, null=True, upload_to='madrasha/logo/'),
        ),
    ]
