# Generated by Django 4.0.6 on 2022-09-24 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='madrasha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='madrasha_teachers', to='accounts.madrasha'),
        ),
    ]
