# Generated by Django 4.0.6 on 2022-10-01 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_madrasha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['-slug']},
        ),
    ]
