# Generated by Django 4.0.6 on 2022-09-02 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_roll', models.CharField(max_length=30)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='transactions.incomecategory')),
                ('madrasha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students_incomes', to='accounts.madrasha')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_categories', to='transactions.incomesubcategory')),
            ],
        ),
    ]
