# Generated by Django 4.1.2 on 2022-10-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_allexpense_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allexpense',
            name='for_month',
            field=models.CharField(blank=True, choices=[('null', 'Null'), ('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=15, null=True),
        ),
    ]
