# Generated by Django 4.0.6 on 2022-09-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_studentincome_student_roll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentincome',
            name='for_months',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
