# Generated by Django 4.0.6 on 2022-09-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_studentincome_for_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentincome',
            name='voucher_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
