# Generated by Django 4.0.6 on 2022-09-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_allexpense_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensesubcategory',
            old_name='sub_category',
            new_name='category',
        ),
    ]
