# Generated by Django 4.0.6 on 2022-09-19 09:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0010_rename_sub_category_expensesubcategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherincome',
            old_name='updated_cat',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='allexpense',
            name='amount',
            field=models.CharField(default='00', max_length=20),
        ),
        migrations.AddField(
            model_name='allexpense',
            name='approved_by',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='allexpense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='allexpense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allexpense',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='allexpense',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='allexpense',
            name='expense_by',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='allexpense',
            name='for_month',
            field=models.CharField(choices=[('null', 'Null'), ('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], default='null', max_length=15),
        ),
        migrations.AddField(
            model_name='allexpense',
            name='for_months',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='allexpense',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='allexpense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='allexpense',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allexpense',
            name='voucher_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
