# Generated by Django 4.1.2 on 2022-10-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_alter_studentincome_for_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allexpense',
            name='amount',
            field=models.CharField(max_length=20),
        ),
    ]
