# Generated by Django 4.1.2 on 2022-10-28 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('settingapp', '0004_remove_books_slug_remove_department_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDistributeToTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=255)),
                ('kitab_name', models.CharField(max_length=255)),
                ('class_time', models.CharField(max_length=255)),
                ('class_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_to_class', to='settingapp.madrashaclasses')),
                ('madrasha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_to_teacher', to='accounts.madrasha')),
            ],
        ),
    ]
