# Generated by Django 4.1.2 on 2022-11-02 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talimats', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examterm',
            unique_together=set(),
        ),
    ]
