# Generated by Django 4.1.2 on 2022-11-16 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('settingapp', '0011_room_floor'),
        ('students', '0004_alter_student_academic_fees'),
        ('talimats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_info_exam_term', to='talimats.examterm')),
                ('exam_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_info_session', to='settingapp.session')),
                ('madrasha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_info_madrasha', to='accounts.madrasha')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_info_student', to='students.student')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_info_class', to='settingapp.madrashaclasses')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_exam_term', to='talimats.examterm')),
                ('exam_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_mark_session', to='settingapp.session')),
                ('madrasha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_mark_madrasha', to='accounts.madrasha')),
                ('result_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_mark_result_info', to='talimats.resultinfo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_mark_student', to='students.student')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_mark_class', to='settingapp.madrashaclasses')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_mark_books', to='settingapp.books')),
            ],
        ),
    ]
