# Generated by Django 4.1.2 on 2022-11-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talimats', '0002_examterm_teachertraining_teacherstaffresponsibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdistributetoteacher',
            name='class_time',
            field=models.TimeField(),
        ),
    ]
