# Generated by Django 4.1.2 on 2022-10-30 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('talimats', '0002_examterm_teachertraining_teacherstaffresponsibility_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dawah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=250)),
                ('duration', models.CharField(max_length=250)),
                ('start_Time', models.CharField(max_length=250)),
                ('place', models.CharField(max_length=250)),
                ('Date', models.CharField(max_length=250)),
                ('managed_by', models.CharField(max_length=250)),
                ('madrasha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.madrasha')),
            ],
        ),
    ]
