# Generated by Django 4.1.2 on 2022-11-01 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('talimats', '0002_examterm_teachertraining_teacherstaffresponsibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examregistration',
            name='madrasha',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='exam_registration_madrasha', to='accounts.madrasha'),
            preserve_default=False,
        ),
    ]
