# Generated by Django 4.1.2 on 2022-10-31 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talimats', '0003_dawah'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dawah',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='dawah',
            old_name='start_Time',
            new_name='start_time',
        ),
    ]
