# Generated by Django 4.1.2 on 2022-11-01 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settingapp', '0005_admitcardinfo'),
        ('talimats', '0003_examregistration_madrasha'),
    ]

    operations = [
        migrations.AddField(
            model_name='examregistration',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registration_session', to='settingapp.session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examregistration',
            name='student_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registration_class', to='settingapp.madrashaclasses'),
            preserve_default=False,
        ),
    ]
