# Generated by Django 4.1.2 on 2022-11-01 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('talimats', '0004_examregistration_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_date', models.DateTimeField()),
                ('chief_of_hall', models.CharField(max_length=255)),
                ('assistant_of_hall', models.CharField(blank=True, max_length=255, null=True)),
                ('room_no', models.CharField(max_length=100)),
                ('madrasha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hall_duty_madrasha', to='accounts.madrasha')),
            ],
        ),
    ]
