# Generated by Django 4.1.2 on 2022-10-31 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('talimats', '0004_rename_date_dawah_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250)),
                ('duration', models.CharField(max_length=250)),
                ('start_time', models.CharField(max_length=250)),
                ('place', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=250)),
                ('managed_by', models.CharField(max_length=250)),
                ('madrasha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.madrasha')),
            ],
        ),
    ]
