# Generated by Django 4.1.2 on 2022-11-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talimats', '0005_extraactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdistributetoteacher',
            name='class_time',
            field=models.TimeField(),
        ),
    ]
