# Generated by Django 4.0.6 on 2022-08-07 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('madrasha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='madrasha_departments', to='accounts.madrasha')),
            ],
        ),
        migrations.CreateModel(
            name='MadrashaClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_classes', to='settingapp.department')),
                ('madrasha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='madrasha_classes', to='accounts.madrasha')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, unique=True)),
                ('shift_time', models.TimeField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_shifts', to='settingapp.department')),
                ('madrasha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='madrasha_shift', to='accounts.madrasha')),
                ('madrasha_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_shifts', to='settingapp.madrashaclasses')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_status', to='settingapp.status')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('madrasha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='madrasha_sessions', to='accounts.madrasha')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_status', to='settingapp.status')),
            ],
        ),
        migrations.CreateModel(
            name='MadrashaGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_madrasha_group', to='settingapp.department')),
                ('madrasha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='madrasha_groups', to='accounts.madrasha')),
                ('madrasha_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_madrasha_group', to='settingapp.madrashaclasses')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='madrasha_group_status', to='settingapp.status')),
            ],
        ),
        migrations.AddField(
            model_name='madrashaclasses',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes_status', to='settingapp.status'),
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, unique=True)),
                ('amount', models.FloatField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_fees', to='settingapp.department')),
                ('madrasha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='madrasha_fees', to='accounts.madrasha')),
                ('madrasha_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_fees', to='settingapp.madrashaclasses')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fees_status', to='settingapp.status')),
            ],
        ),
        migrations.CreateModel(
            name='ExamRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_input', models.TextField(max_length=2000)),
                ('madrasha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='madrasha_exam_rules', to='accounts.madrasha')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examrules_status', to='settingapp.status')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('madrasha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='madrasha_designations', to='accounts.madrasha')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designations_status', to='settingapp.status')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='settingapp.status'),
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_books', to='settingapp.department')),
                ('madrasha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='madrasha_books', to='accounts.madrasha')),
                ('madrasha_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_books', to='settingapp.madrashaclasses')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books_status', to='settingapp.status')),
            ],
        ),
    ]
