# Generated by Django 4.0.6 on 2022-08-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settingapp', '0002_remove_books_status_remove_department_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
