# Generated by Django 4.0.6 on 2022-08-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingapp', '0003_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
