# Generated by Django 4.1.2 on 2022-11-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportdetail',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='vehicleinfo',
            name='time',
            field=models.TimeField(),
        ),
    ]
