# Generated by Django 4.1.2 on 2022-11-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportdetail',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='vehicleinfo',
            name='time',
        ),
        migrations.AddField(
            model_name='vehicleinfo',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
