# Generated by Django 4.1.2 on 2022-11-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_transportdetail_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportdetail',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
