# Generated by Django 4.1.2 on 2022-11-02 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_alter_transportdetail_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleinfo',
            name='time',
        ),
    ]
