# Generated by Django 4.1.2 on 2022-11-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_remove_vehicleinfo_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinfo',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
