# Generated by Django 4.1.2 on 2022-11-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_vehicleinfo_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportdetail',
            name='start_time',
        ),
    ]
