# Generated by Django 4.1.2 on 2022-11-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_remove_transportdetail_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportdetail',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
