# Generated by Django 4.1.2 on 2022-11-04 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_transportdetail_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportdetail',
            name='start_time',
        ),
    ]
